[package]
name = "multisnake"
version = "0.1.0"
authors = ["Ponas Kovas"]
edition = "2018"

[dependencies]
term_size = { version = "0.3.1", optional = true }
rand = { version = "0.7.0", optional = true }
crossterm_input = { version = "0.3.9", optional = true }
clap = "2.33.0"
scopeguard = { version = "1.0.0", optional = true }
dns-lookup = { version = "1.0.1", optional = true }

[features]
default = ["client", "server"]

# compiles and adds client side code, launch with --client
client = ["term_size", "crossterm_input", "scopeguard", "dns-lookup"]
# compiles and adds server side code, launch with --server
server = ["rand"]
# Make sure to have at least 1 of these enabled, or you'll end up with an empty binary